name: git-hygiene

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  git-hygiene:
    uses: saagpatel/sovereign/.github/workflows/git-hygiene.yml@f27de0d13192c0ae42e94cdec85b8c224971bc8a
